version: "3.9"
services:
  backend:
    image: notelix:latest
    ports:
      - "18555:80"
  postgres:
    image: "postgres:14"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "18556:5432"
  meilisearch:
    image: "getmeili/meilisearch:v0.25.2"
volumes:
  postgres-data:
