FROM node:22.23.2-alpine3.24

RUN apk add --no-cache python3 make g++
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --non-interactive && yarn cache clean

COPY . ./

EXPOSE 3000
CMD ["npm", "run", "start:dev"]
