version: "3.9"
services:
  backend:
    image: kevinwang15/notelix:prod
    restart: always
    ports:
      - "18555:3000"
    links:
      - "postgres"
      - "meilisearch"
    env_file:
      - .env.prod
    volumes:
      - ./ormconfig.js:/app/ormconfig.js
      - ./.env.prod:/app/.env
      - data:/data
  postgres:
    image: "postgres:14"
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "18556:5432"
  meilisearch:
    image: "getmeili/meilisearch:v0.25.2"
    restart: always
    volumes:
      - meili:/data.ms
    ports:
      - "18557:7700"
volumes:
  postgres-data:
  data:
  meili:
networks:
  default:
    external:
      name: notelix
