FROM node:26.7.0-alpine3.24

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --non-interactive && yarn cache clean

COPY . ./

EXPOSE 3000
CMD ["npm", "run", "start:dev"]
