version: "3.9"
services:
  backend:
    image: notelix:agent
    restart: always
#    command: [ "sh", "-c", "sleep 3000" ]
    ports:
      - "18565:3000"
    links:
      - "postgres"
      - "meilisearch"
    env_file:
      - .env.agent
    environment:
      - RUN_MODE=AGENT
      - AGENT_SYNC_URL_OVERRIDE=http://notelix-dev_backend_1:3000
    volumes:
      - ./src:/app/src
      - ./tools:/app/tools
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
      - ./ormconfig.js:/app/ormconfig.js
      - ./.env.agent:/app/.env
      - data:/data
  postgres:
    image: "postgres:14"
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "18566:5432"
  meilisearch:
    image: "getmeili/meilisearch:v0.25.2"
    restart: always
    volumes:
      - meili:/data.ms
    ports:
      - "18567:7700"
volumes:
  postgres-data:
  data:
  meili:
networks:
  default:
    external:
      name: notelix
